/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e4e9ed",
        "surface-container": "#eaeef2",
        "on-surface": "#171c1f",
        "on-error": "#ffffff",
        "outline-variant": "#bec8ca",
        "on-tertiary-fixed": "#00201e",
        "primary-fixed-dim": "#82d3de",
        "on-secondary": "#ffffff",
        "surface": "#f6fafe",
        "surface-tint": "#006972",
        "on-surface-variant": "#3e494a",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f0f4f8",
        "background": "#f6fafe",
        "on-secondary-container": "#672c00",
        "inverse-on-surface": "#edf1f5",
        "on-primary-fixed": "#001f23",
        "inverse-primary": "#82d3de",
        "on-secondary-fixed": "#331200",
        "error": "#ba1a1a",
        "tertiary-container": "#286d67",
        "outline": "#6f797a",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dfe3e7",
        "on-primary-container": "#9becf7",
        "surface-bright": "#f6fafe",
        "on-background": "#171c1f",
        "secondary-fixed": "#ffdbc9",
        "on-primary-fixed-variant": "#004f56",
        "tertiary-fixed-dim": "#90d3cb",
        "secondary": "#9b4500",
        "tertiary": "#01544f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#a9ece4",
        "tertiary-fixed": "#acefe7",
        "primary-fixed": "#9ff0fb",
        "on-tertiary-fixed-variant": "#00504b",
        "inverse-surface": "#2c3134",
        "surface-dim": "#d6dade",
        "on-secondary-fixed-variant": "#763300",
        "surface-variant": "#dfe3e7",
        "on-primary": "#ffffff",
        "secondary-container": "#fc8a40",
        "secondary-fixed-dim": "#ffb68d",
        "primary-container": "#006d77",
        "primary": "#00535b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
